#!/bin/bash

function comparison_branch() {
  for branch in origin/development development origin/main main origin/master master; do
    if git show-ref --verify --quiet refs/remotes/$branch || git show-ref --verify --quiet refs/heads/$branch; then
      echo $branch
      break
    fi
  done
}

if [ $# -eq 0 ]; then
  a="@"
  b=$(comparison_branch)
elif [ $# -eq 1 ]; then
  a="@"
  b=$1
else
  a=$2
  b=$1
fi

commits=$(git rev-list $a --not $b --max-count=1)
if [ -z $commits ]; then
  commits=$(git rev-list $b --not $a --max-count=1)
  if [ -z $commits ]; then
     git l ^$a~ $a
  else
    root_commit=$(git rev-list $b --not $a --reverse | head -n 1)
    git l ^$root_commit~2 $b $a
  fi
else
  root_commit=$(git rev-list $a --not $b --reverse | head -n 1)
  git l ^$root_commit~2 $a $b
fi

